spring:
  application:
    name: resource-server1
    
  # CONFIGURA SEGURANCA   
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:8081
          

# CONFIGURA SERVIDOR    
server:
  port: ${SERVER_PORT:8083}
  
  
  
# CONFIGURA EUREKA CLIENTE
eureka:
  client:
    fetch-registry: true 
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
    hostname: localhost
    
 
# CONFIGURA SPRING DOC PARA RODAR NO GATEWAY
springdoc:
  api-docs:
    path: /v3/api-docs #URL usada ​​para carregar o swagger ui deste serviço pelo gateway de API 
  swagger-ui:
    path: /swagger-ui.html
    
    
# HABILITA LOG
logging:
  level:
    org: 
      springframework: 
        security: TRACE
        